name: Pull Request Check # 워크플로우 이름

on: # 워크플로우 실행 트리거
  pull_request: # pull_request 가 진행될때
    types: [opend, synchronize] # PR 생성되고 업데이트 될 때 
jobs:  # 작업 정의
  check: 
    runs-on: ubuntu-lastest # 우분투 환경
    permissions: # 권한 설정
      pull-requests: write # PR에 쓰기 권한 설정 
    steps: # 작업단계
      - uses: actions/github-script@v7
        with:
          script: | # 스크립트 시작 
            const pull_request = context.payload.pull_request; # pull_request 객체 가져오기

            if(pull_request === undefind) { # pull_request 가 없는 경우 
              console.log("This is not a pull request);
              return; # 종료 
            }

            const body = pull_request.body;

            if (!body) {
              // PR에 코멘트를 추가합니다.
              await github.rest.issues.createComment({ //PR 코멘트
                owner: context.repo.owner, // 저장소 소유자 
                repo: context.repo.repo, // 저장소 이름 
                issue_number: pull_request.number, //PR 번호
                body: "해당 PR은 가이드라인을 준수하지 않았습니다. 때문에 PR을 닫도록 하겠습니다. 가이드라인 준수해서 다시 PR 요청을 해주세요.
              });
              
              // PR을 닫습니다.
              await github.rest.issues.createComment({ //PR 코멘트
                owner: context.repo.owner, // 저장소 소유자 
                repo: context.repo.repo, // 저장소 이름 
                pull_number: pull_request.number, //PR 번호
                state: "closed" //상태를 닫습니다.
                });
            }
